export const pets = [  {
    name: "Jennifer",
    img: "../../src/images/pets-jennifer.png",
    category: "dogs",
    type: "Dog",
    breed: "Labrador",
    description:
      "Jennifer is a sweet 2 months old Labrador that is patiently waiting to find a new forever home.",
    age: "2 months",
    inoculations: "none",
    diseases: "none",
    parasites: "none",
  },
    {
    name: "Luna",
    img: "../../src/images/pets-timmy.png",
    category: "cats",
    type: "Cat",
    breed: "British Shorthair",
    description:
      "Luna is a gentle and affectionate cat who would love to find a forever home.",
    age: "8 months",
    inoculations: "rabies",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Woody",
    img: "../../src/images/pets-woody.png",
    category: "dogs",
    type: "Dog",
    breed: "Golden Retriever",
    description:
      "Woody is a handsome boy who knows basic commands and is looking for a loving family.",
    age: "3 years 6 months",
    inoculations: ["adenovirus", "distemper"],
    diseases: "right back leg mobility reduced",
    parasites: "none",
  },
  {
    name: "Scarlett",
    img: "../../src/images/pets-scarlet.png",
    category: "dogs",
    type: "Dog",
    breed: "Jack Russell Terrier",
    description:
      "Scarlett is a happy, playful girl who will make a loyal companion and a wonderful family dog.",
    age: "3 months",
    inoculations: "parainfluenza",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Charly",
    img: "../../src/images/pets-charly.png",
    category: "dogs",
    type: "Dog",
    breed: "Jack Russell Terrier",
    description:
      "Charly is an energetic boy who loves to run and play. He would be happy with an active family.",
    age: "8 years",
    inoculations: ["bordetella bronchiseptica", "leptospirosis"],
    diseases: ["deafness", "blindness"],
    parasites: ["lice", "fleas"],
  },
  {
    name: "Max",
    img: "../../src/images/pets-jennifer.png",
    category: "dogs",
    type: "Dog",
    breed: "Labrador",
    description:
      "Max is a friendly Labrador who loves long walks, playing with toys and spending time with people.",
    age: "4 years",
    inoculations: "rabies",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Buddy",
    img: "../../src/images/pets-woody.png",
    category: "dogs",
    type: "Dog",
    breed: "Golden Retriever",
    description:
      "Buddy is a cheerful Golden Retriever who loves children and enjoys spending time outdoors.",
    age: "2 years",
    inoculations: "none",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Cooper",
    img: "../../src/images/pets-scarlet.png",
    category: "dogs",
    type: "Dog",
    breed: "Jack Russell Terrier",
    description:
      "Cooper is an active and curious dog who enjoys playing outdoors and meeting new people.",
    age: "1 year 8 months",
    inoculations: "parainfluenza",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Katrine",
    img: "../../src/images/pets-katrine.png",
    category: "cats",
    type: "Cat",
    breed: "British Shorthair",
    description:
      "Katrine is a beautiful girl with soft fur who loves cuddles and relaxing in someone's hands.",
    age: "6 months",
    inoculations: "panleukopenia",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Timmy",
    img: "../../src/images/pets-timmy.png",
    category: "cats",
    type: "Cat",
    breed: "British Shorthair",
    description:
      "Timmy is an adorable grey British Shorthair male. He loves to play, snuggle and be held.",
    age: "2 years 3 months",
    inoculations: ["calicivirus", "viral rhinotracheitis"],
    diseases: "kidney stones",
    parasites: "none",
  },
  {
    name: "Freddie",
    img: "../../src/images/pets-freddie.png",
    category: "cats",
    type: "Cat",
    breed: "British Shorthair",
    description:
      "Freddie is a little shy at first, but very sweet when he warms up. He is looking for his forever home.",
    age: "2 months",
    inoculations: "rabies",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Oliver",
    img: "../../src/images/pets-katrine.png",
    category: "cats",
    type: "Cat",
    breed: "British Shorthair",
    description:
      "Oliver is a calm and affectionate cat who enjoys quiet evenings and spending time with people.",
    age: "1 year",
    inoculations: "none",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Milo",
    img: "../../src/images/pets-timmy.png",
    category: "cats",
    type: "Cat",
    breed: "British Shorthair",
    description:
      "Milo is a playful cat who enjoys chasing toys and relaxing in sunny places.",
    age: "3 years",
    inoculations: "rabies",
    diseases: "none",
    parasites: "none",
  },
    {
    name: "Sophia",
    img: "../../src/images/sophia.png",
    category: "dogs",
    type: "Dog",
    breed: "Shih tzu",
    description:
      "Sophia is full of energy and is looking for her forever home to live out the best years of her life.",
    age: "1 month",
    inoculations: "parvovirus",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Leo",
    img: "../../src/images/pets-freddie.png",
    category: "cats",
    type: "Cat",
    breed: "British Shorthair",
    description:
      "Leo is a gentle and curious cat who likes attention and quiet evenings with his family.",
    age: "1 year 6 months",
    inoculations: "panleukopenia",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Simba",
    img: "../../src/images/pets-katrine.png",
    category: "cats",
    type: "Cat",
    breed: "British Shorthair",
    description:
      "Simba is a friendly cat who loves playing and being around people.",
    age: "2 years",
    inoculations: "none",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Jennifer",
    img: "../../src/images/pets-jennifer.png",
    category: "dogs",
    type: "Dog",
    breed: "Labrador",
    description:
      "Jennifer is a sweet 2 months old Labrador that is patiently waiting to find a new forever home.",
    age: "2 months",
    inoculations: "none",
    diseases: "none",
    parasites: "none",
  },
    {
    name: "Luna",
    img: "../../src/images/pets-timmy.png",
    category: "cats",
    type: "Cat",
    breed: "British Shorthair",
    description:
      "Luna is a gentle and affectionate cat who would love to find a forever home.",
    age: "8 months",
    inoculations: "rabies",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Woody",
    img: "../../src/images/pets-woody.png",
    category: "dogs",
    type: "Dog",
    breed: "Golden Retriever",
    description:
      "Woody is a handsome boy who knows basic commands and is looking for a loving family.",
    age: "3 years 6 months",
    inoculations: ["adenovirus", "distemper"],
    diseases: "right back leg mobility reduced",
    parasites: "none",
  },
  {
    name: "Scarlett",
    img: "../../src/images/pets-scarlet.png",
    category: "dogs",
    type: "Dog",
    breed: "Jack Russell Terrier",
    description:
      "Scarlett is a happy, playful girl who will make a loyal companion and a wonderful family dog.",
    age: "3 months",
    inoculations: "parainfluenza",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Charly",
    img: "../../src/images/pets-charly.png",
    category: "dogs",
    type: "Dog",
    breed: "Jack Russell Terrier",
    description:
      "Charly is an energetic boy who loves to run and play. He would be happy with an active family.",
    age: "8 years",
    inoculations: ["bordetella bronchiseptica", "leptospirosis"],
    diseases: ["deafness", "blindness"],
    parasites: ["lice", "fleas"],
  },
  {
    name: "Max",
    img: "../../src/images/pets-jennifer.png",
    category: "dogs",
    type: "Dog",
    breed: "Labrador",
    description:
      "Max is a friendly Labrador who loves long walks, playing with toys and spending time with people.",
    age: "4 years",
    inoculations: "rabies",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Buddy",
    img: "../../src/images/pets-woody.png",
    category: "dogs",
    type: "Dog",
    breed: "Golden Retriever",
    description:
      "Buddy is a cheerful Golden Retriever who loves children and enjoys spending time outdoors.",
    age: "2 years",
    inoculations: "none",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Cooper",
    img: "../../src/images/pets-scarlet.png",
    category: "dogs",
    type: "Dog",
    breed: "Jack Russell Terrier",
    description:
      "Cooper is an active and curious dog who enjoys playing outdoors and meeting new people.",
    age: "1 year 8 months",
    inoculations: "parainfluenza",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Katrine",
    img: "../../src/images/pets-katrine.png",
    category: "cats",
    type: "Cat",
    breed: "British Shorthair",
    description:
      "Katrine is a beautiful girl with soft fur who loves cuddles and relaxing in someone's hands.",
    age: "6 months",
    inoculations: "panleukopenia",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Timmy",
    img: "../../src/images/pets-timmy.png",
    category: "cats",
    type: "Cat",
    breed: "British Shorthair",
    description:
      "Timmy is an adorable grey British Shorthair male. He loves to play, snuggle and be held.",
    age: "2 years 3 months",
    inoculations: ["calicivirus", "viral rhinotracheitis"],
    diseases: "kidney stones",
    parasites: "none",
  },
  {
    name: "Freddie",
    img: "../../src/images/pets-freddie.png",
    category: "cats",
    type: "Cat",
    breed: "British Shorthair",
    description:
      "Freddie is a little shy at first, but very sweet when he warms up. He is looking for his forever home.",
    age: "2 months",
    inoculations: "rabies",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Oliver",
    img: "../../src/images/pets-katrine.png",
    category: "cats",
    type: "Cat",
    breed: "British Shorthair",
    description:
      "Oliver is a calm and affectionate cat who enjoys quiet evenings and spending time with people.",
    age: "1 year",
    inoculations: "none",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Milo",
    img: "../../src/images/pets-timmy.png",
    category: "cats",
    type: "Cat",
    breed: "British Shorthair",
    description:
      "Milo is a playful cat who enjoys chasing toys and relaxing in sunny places.",
    age: "3 years",
    inoculations: "rabies",
    diseases: "none",
    parasites: "none",
  },
    {
    name: "Sophia",
    img: "../../src/images/sophia.png",
    category: "dogs",
    type: "Dog",
    breed: "Shih tzu",
    description:
      "Sophia is full of energy and is looking for her forever home to live out the best years of her life.",
    age: "1 month",
    inoculations: "parvovirus",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Leo",
    img: "../../src/images/pets-freddie.png",
    category: "cats",
    type: "Cat",
    breed: "British Shorthair",
    description:
      "Leo is a gentle and curious cat who likes attention and quiet evenings with his family.",
    age: "1 year 6 months",
    inoculations: "panleukopenia",
    diseases: "none",
    parasites: "none",
  },
  {
    name: "Simba",
    img: "../../src/images/pets-katrine.png",
    category: "cats",
    type: "Cat",
    breed: "British Shorthair",
    description:
      "Simba is a friendly cat who loves playing and being around people.",
    age: "2 years",
    inoculations: "none",
    diseases: "none",
    parasites: "none",
  },
];